TIMING:
  TAP_MILLISEC: 200
  DOUBLE_TAP_MILLISEC: 550

MAPPINGS:
  - KEY: KEY_ENTER
    TAP: KEY_ENTER
    HOLD: KEY_RIGHTCTRL

  - KEY: KEY_CAPSLOCK
    TAP: KEY_LEFTCTRL
    HOLD: KEY_LEFTCTRL

  - KEY: KEY_LEFTCTRL
    TAP: KEY_CAPSLOCK
    HOLD: KEY_LEFTCTRL

  - KEY: KEY_LEFTSHIFT
    TAP: KEY_ESC
    HOLD: KEY_LEFTSHIFT

  - KEY: KEY_RIGHTSHIFT
    TAP: KEY_ESC
    HOLD: KEY_RIGHTSHIFT

  - KEY: KEY_D
    TAP: KEY_D
    HOLD: KEY_RIGHTCTRL

  - KEY: KEY_F
    TAP: KEY_F
    HOLD: KEY_RIGHTALT

  - KEY: KEY_J
    TAP: KEY_J
    HOLD: KEY_LEFTALT

  - KEY: KEY_K
    TAP: KEY_K
    HOLD: KEY_LEFTCTRL

  - KEY: KEY_SPACE
    TAP: KEY_SPACE
    HOLD: KEY_RIGHTSHIFT