TIMING:
  TAP_MILLISEC: 200
  DOUBLE_TAP_MILLISEC: 150

MAPPINGS:
  - KEY: KEY_ENTER
    TAP: KEY_ENTER
    HOLD: KEY_RIGHTCTRL

  - KEY: KEY_CAPSLOCK
    TAP: KEY_LEFTCTRL
    HOLD: KEY_LEFTCTRL

  - KEY: KEY_LEFTCTRL
    TAP: KEY_CAPSLOCK
    HOLD: KEY_LEFTCTRL

  - KEY: KEY_LEFTSHIFT
    TAP: KEY_ESC
    HOLD: KEY_LEFTSHIFT

  - KEY: KEY_RIGHTSHIFT
    TAP: KEY_ESC
    HOLD: KEY_RIGHTSHIFT